// This file is autogenerated. Changes will be overwritten.
#include "6YEA5652QU/moc_DCommit.cpp"
#include "6YEA5652QU/moc_DTag.cpp"
#include "6YEA5652QU/moc_TagItemDelegate.cpp"
#include "6YEA5652QU/moc_WFileTag.cpp"
